# Generated by Django 4.0.4 on 2022-05-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customusermodel_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
